on: [push]

jobs:
  deploy_with_contrast_job:
    runs-on: ubuntu-latest
    name: Deploy Azure Spring Cloud Application with Contrast Security
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Contrast Security Azure Spring Cloud Deployment
        uses: ./ # Uses an action in the root directory
        id: contrast-deployment
        with:
          github-user-repo: "$GITHUB_REPOSITORY"
          github-developer-token: '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'
          application-name: 'springone-petclinic-mark-testing'
          spring-cloud-service-name: 'mark-spring-cloud-test'
          application-artifact-location: 'main/spring-petclinic-2.4.5.jar'
          azure-application-jvm-options: '-javaagent:/persistent/apm/contrast.jar'
          contrast-security-credentials-file: '{"contrast_api_url": "https://eval.contrastsecurity.com/Contrast","contrast_api_username": "agent_a8cd7a84-5cc2-4df6-b5d9-c016cc2c6f53@Marktomczaorg","contrast_api_api_key": "DOeAUIavVy5NmqNA11bnuKemAq946yn7","contrast_api_service_key": "K7E3Y5QDM6MUMVUB","contrast_agent_java_standalone_app_name": "springone-workshop-petclinic-new","contrast_application_version": "1"}'
          azure-credentials-file: '{"azure_application_id": "4d43ffdc-1eda-4bce-9796-8202eee0ed19","azure_tenant_id": "48d090fb-932b-4e13-9c76-4aa018e3e1e8","azure_client_secret": "zk_B-gb._08qz-IXu14ErB~JVcQed7~ASc","azure_subscription_id": "fa9b4730-faca-44b9-a408-28c675e4a6a1","azure_resource_group_name": "azure-spring-cloud-sa","azure_region": "EAST US"}'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.contrast-deployment.outputs.time }} wthen this action was run."
