on: [push]

jobs:
  deploy_with_contrast_job:
    runs-on: ubuntu-latest
    name: Deploy Azure Spring Cloud Application with Contrast Security
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Contrast Security Azure Spring Cloud Deployment
        uses: ./ # Uses an action in the root directory
        id: contrast-deployment
        with:
          github-developer-token: ${{ secrets.DEV_TOKEN }}
          application-name: 'springone-petclinic-mark-testing'
          spring-cloud-service-name: 'mark-spring-cloud-test'
          application-artifact-location: 'spring-petclinic-2.4.5.jar'
          contrast-security-credentials-file: ${{ secrets.CONTRAST_CREDS_FILE }}
          azure-credentials-file: ${{ secrets.AZURE_CREDS_FILE }}
